# -*- coding: utf-8 -*-
"""2. Input Nilai & Nilai Tertinggi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7fvbLNjSrYBICvw6gn7ylKaReei2yx2
"""

# Fungsi untuk menghitung rata-rata dari 3 nilai pelajaran
def hitung_rata_rata(nilai1, nilai2, nilai3):
    rata_rata = (nilai1 + nilai2 + nilai3) / 3
    return rata_rata

# Fungsi untuk menentukan status kelulusan berdasarkan rata-rata
def status_kelulusan(rata_rata):
    if rata_rata >= 75:
        return "Lulus"
    else:
        return "Tidak Lulus"

# Input nilai pelajaran dari user (tipe data integer atau float)
nilai1 = float(input("Masukkan nilai pelajaran 1: "))
nilai2 = float(input("Masukkan nilai pelajaran 2: "))
nilai3 = float(input("Masukkan nilai pelajaran 3: "))

# Hitung rata-rata
rata_rata = hitung_rata_rata(nilai1, nilai2, nilai3)

# Tentukan status kelulusan
status = status_kelulusan(rata_rata)

# Tampilkan hasil
print(f"Rata-rata nilai: {rata_rata:.2f}")
print(f"Status kelulusan: {status}")