# -*- coding: utf-8 -*-
"""3_faktorial_rekursif.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZQxqI-46vHGWM2tJrbthn8JIc-7O5RM
"""

# Fungsi rekursif untuk menghitung faktorial
def faktorial(n):
    if n == 0:
        return 1
    else:
        return n * faktorial(n - 1)

# Contoh penggunaan
angka = int(input("Masukkan angka untuk dihitung faktorialnya: "))
hasil = faktorial(angka)
print(f"Faktorial dari {angka} adalah {hasil}")