# -*- coding: utf-8 -*-
"""4_nilai_tertinggi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192IbkwuT9WrBBqnw_VS_XvmJUYdofGG5
"""

# Program mencari nilai tertinggi dari 5 siswa

# Membuat list kosong untuk menyimpan nilai
nilai_siswa = []

# Input nilai sebanyak 5 kali
for i in range(5):
    nilai = int(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Mencari nilai tertinggi dan indeksnya
nilai_tertinggi = max(nilai_siswa)
siswa_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1

# Menampilkan hasil
print(f"Nilai tertinggi adalah: {nilai_tertinggi}")
print(f"Didapatkan oleh siswa ke-{siswa_tertinggi}")