# -*- coding: utf-8 -*-
"""5_total_belanja.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pmvh1aJbPzBA6BqL0Thd_2IDySPBTsSv
"""

# Program menghitung total harga pembelian 3 barang

# Input harga masing-masing barang
harga1 = float(input("Masukkan harga barang ke-1: "))
harga2 = float(input("Masukkan harga barang ke-2: "))
harga3 = float(input("Masukkan harga barang ke-3: "))

# Hitung total
total = harga1 + harga2 + harga3

# Tampilkan total pembayaran
print(f"Total pembayaran: Rp{total:,.2f}")