# -*- coding: utf-8 -*-
"""uts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkvDcq_mJfylCoRAj6_b7a-bLJvkq7ob
"""

# Program Diskon E-Commerce

# Meminta input total belanja dari user
total_belanja = float(input("Masukkan total belanja Anda (Rp): "))

# Mengecek apakah total belanja memenuhi syarat untuk diskon
if total_belanja > 500000:
    diskon = total_belanja * 0.10
    total_bayar = total_belanja - diskon
    print(f"Anda mendapat diskon 10%. Total bayar: Rp{total_bayar:,.2f}")
else:
    print(f"Tidak ada diskon. Total bayar: Rp{total_belanja:,.2f}")

# Fungsi untuk menghitung rata-rata dari 3 nilai pelajaran
def hitung_rata_rata(nilai1, nilai2, nilai3):
    rata_rata = (nilai1 + nilai2 + nilai3) / 3
    return rata_rata

# Fungsi untuk menentukan status kelulusan berdasarkan rata-rata
def status_kelulusan(rata_rata):
    if rata_rata >= 75:
        return "Lulus"
    else:
        return "Tidak Lulus"

# Input nilai pelajaran dari user (tipe data integer atau float)
nilai1 = float(input("Masukkan nilai pelajaran 1: "))
nilai2 = float(input("Masukkan nilai pelajaran 2: "))
nilai3 = float(input("Masukkan nilai pelajaran 3: "))

# Hitung rata-rata
rata_rata = hitung_rata_rata(nilai1, nilai2, nilai3)

# Tentukan status kelulusan
status = status_kelulusan(rata_rata)

# Tampilkan hasil
print(f"Rata-rata nilai: {rata_rata:.2f}")
print(f"Status kelulusan: {status}")

# Fungsi rekursif untuk menghitung faktorial
def faktorial(n):
    if n == 0:
        return 1
    else:
        return n * faktorial(n - 1)

# Contoh penggunaan
angka = int(input("Masukkan angka untuk dihitung faktorialnya: "))
hasil = faktorial(angka)
print(f"Faktorial dari {angka} adalah {hasil}")

# Membuat list kosong untuk menyimpan nilai
nilai_siswa = []

# Menggunakan perulangan untuk input nilai 5 siswa
for i in range(5):
    nilai = int(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Mencari nilai tertinggi
nilai_tertinggi = max(nilai_siswa)

# Menentukan siswa ke berapa yang mendapat nilai tertinggi
indeks_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1  # ditambah 1 karena index dimulai dari 0

# Menampilkan hasil
print(f"Nilai tertinggi adalah {nilai_tertinggi}, diperoleh oleh siswa ke-{indeks_tertinggi}")

# Input harga 3 barang dari pengguna
harga1 = float(input("Masukkan harga barang pertama: "))
harga2 = float(input("Masukkan harga barang kedua: "))
harga3 = float(input("Masukkan harga barang ketiga: "))

# Menghitung total harga
total = harga1 + harga2 + harga3

# Menampilkan total pembayaran
print(f"Total harga yang harus dibayar adalah: Rp{total}")